version: "3.8"
services:
  # postgres db
  postgres:
    image: postgres:15-alpine
    container_name: auth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"  #ignore dev only
    volumes:
      - postgres_data:/var/lib/postgresql/data   
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: 
      - auth_network  

    #  backend api
  backend:
    build: .
    container_name: auth_backend
    restart: unless-stopped
    ports: 
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: auth_db
      DB_USER: postgres
      DB_PASSWORD: postgres123
      JWT_ACCESS_SECRET: dev_access_secret        #dev only ignore
      JWT_REFRESH_SECRET: dev_refresh_secret       #dev only ignore
      JWT_ACCESS_EXPIRY: 15m
      JWT_REFRESH_EXPIRY: 7d
      CLIENT_URL: http://localhost:3000

    depends_on: 
      postgres:
        condition: service_healthy

    volumes:
      - ./src:/app/src

    networks:
      - auth_network

volumes:
  postgres_data:     

networks:
  auth_network: 
    driver: bridge





 


